import type { MediaKey } from '@/lib/media'

export const categories = [
  { id: 'all', label: 'All' },
  { id: 'concert', label: 'Concert' },
  { id: 'shoot', label: 'Shoots' },
] as const

export type Category = Exclude<(typeof categories)[number]['id'], 'all'>
export type GalleryItem = { key: MediaKey; category: Category }

// Display order for the "All" tab. Credits come from content/media.json.
export const gallery: GalleryItem[] = [
  { key: 'c-gl-01', category: 'concert' },
  { key: 'c-da-02', category: 'concert' },
  { key: 'c-gl-02', category: 'concert' },
  { key: 'c-da-03', category: 'concert' },
  { key: 's-gl-01', category: 'shoot' },
  { key: 'c-gl-03', category: 'concert' },
  { key: 'c-da-05', category: 'concert' },
  { key: 'c-gl-04', category: 'concert' },
  { key: 'c-da-08', category: 'concert' },
  { key: 's-gl-02', category: 'shoot' },
  { key: 'c-gl-05', category: 'concert' },
  { key: 'c-ji-01', category: 'concert' },
  { key: 'c-gl-06', category: 'concert' },
  { key: 'c-ji-02', category: 'concert' },
  { key: 's-gl-03', category: 'shoot' },
  { key: 'c-gl-07', category: 'concert' },
  { key: 'c-ji-03', category: 'concert' },
  { key: 'c-gl-08', category: 'concert' },
  { key: 'c-ji-04', category: 'concert' },
  { key: 's-gl-04', category: 'shoot' },
  { key: 'c-gl-09', category: 'concert' },
  { key: 'c-ji-05', category: 'concert' },
  { key: 'c-gl-10', category: 'concert' },
  { key: 'c-ji-06', category: 'concert' },
  { key: 's-gl-05', category: 'shoot' },
  { key: 'c-gl-11', category: 'concert' },
  { key: 'c-ji-07', category: 'concert' },
  { key: 'c-gl-12', category: 'concert' },
  { key: 'c-ji-08', category: 'concert' },
  { key: 's-ji-01', category: 'shoot' },
  { key: 'c-gl-13', category: 'concert' },
  { key: 'c-ji-09', category: 'concert' },
  { key: 'c-gl-14', category: 'concert' },
  { key: 'c-ji-10', category: 'concert' },
  { key: 's-ji-02', category: 'shoot' },
  { key: 'c-gl-15', category: 'concert' },
  { key: 'c-ji-11', category: 'concert' },
  { key: 'c-ji-12', category: 'concert' },
  { key: 'c-ji-13', category: 'concert' },
  { key: 's-ji-03', category: 'shoot' },
  { key: 'c-ji-14', category: 'concert' },
  { key: 'c-ji-15', category: 'concert' },
  { key: 'c-ji-16', category: 'concert' },
  { key: 'c-ji-17', category: 'concert' },
  { key: 's-ji-04', category: 'shoot' },
  { key: 'c-ji-18', category: 'concert' },
  { key: 'c-ji-19', category: 'concert' },
  { key: 'c-ji-20', category: 'concert' },
  { key: 'c-ji-21', category: 'concert' },
  { key: 's-ji-05', category: 'shoot' },
  { key: 'c-ji-22', category: 'concert' },
  { key: 'c-ji-23', category: 'concert' },
  { key: 'c-ji-24', category: 'concert' },
  { key: 'c-ji-25', category: 'concert' },
  { key: 's-ji-06', category: 'shoot' },
  { key: 'c-ji-26', category: 'concert' },
  { key: 'c-ji-27', category: 'concert' },
  { key: 'c-ji-28', category: 'concert' },
  { key: 'c-ji-29', category: 'concert' },
  { key: 's-ji-07', category: 'shoot' },
  { key: 'c-ji-30', category: 'concert' },
  { key: 'c-ji-31', category: 'concert' },
  { key: 'c-ji-32', category: 'concert' },
  { key: 'c-ji-33', category: 'concert' },
  { key: 's-ji-08', category: 'shoot' },
  { key: 'c-ji-34', category: 'concert' },
  { key: 'c-ji-35', category: 'concert' },
  { key: 'c-ji-36', category: 'concert' },
  { key: 'c-ji-37', category: 'concert' },
  { key: 's-ji-09', category: 'shoot' },
  { key: 's-ji-10', category: 'shoot' },
  { key: 's-ji-11', category: 'shoot' },
  { key: 's-ji-12', category: 'shoot' },
  { key: 's-ji-13', category: 'shoot' },
  { key: 's-ji-14', category: 'shoot' },
]
